- name: "DPKG Update"
  hosts: laptops
  tasks:
    - name: "Update package cache"
      ansible.builtin.apt:
        update_cache: true
    - name: "Run package Update"
      ansible.builtin.apt:
        upgrade: full
    - name: "reboot if needed"
      ansible.builtin.reboot:
        reboot_timeout: 300
    - name: "remove obsolete packages"
      ansible.builtin.apt:
        autoremove: true
