#SPDX-License-Identifier: MIT-0
---
# tasks file for platform-io
- name: "Install VSCode"
  ansible.builtin.apt:
    name: code
    state: present
- name: "Install PlatformIO for user: user"
  ansible.builtin.command:
    cmd: "sudo -u user code --install-extension platformio.platformio-ide"
- name: "Install PlatformIO for user: laptop"
  ansible.builtin.command:
    cmd: "sudo -u laptop code --install-extension platformio.platformio-ide"
